version: '3'
services:
    cmsworks-nginx:
        build:
            context: ./docker/development
            dockerfile: nginx.docker
        volumes:
            - ./app:/app:cached
        depends_on:
            - cmsworks-php-fpm
        ports:
            - "80:80"
    cmsworks-php-fpm:
        build:
            context: ./docker/development
            dockerfile: php-fpm.docker
        volumes:
            - ./app:/app:cached
        depends_on:
            - cmsworks-postgres
            - mailer
    cmsworks-postgres:
        image: postgres:11.2-alpine
        volumes:
            - cmsworks-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: developer
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: cmsworks
        ports:
            - "54321:5432"
    mailer:
        image: mailhog/mailhog
        ports:
            - "8082:8025"
volumes:
    cmsworks-postgres:
    composer:

networks:
    cmsworks_default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.220.0/28
