version: '3'
services:
    cmsworks-nginx:
        build:
            context: ./docker/development
            dockerfile: nginx.docker
        volumes:
            - ./app:/app:cached
        depends_on:
            - cmsworks-php-fpm
        ports:
            - "80:80"
    cmsworks-php-fpm:
        build:
            context: ./docker/development
            dockerfile: php-fpm.docker
        volumes:
            - ./app:/app:cached
        depends_on:
            - cmsworks-postgres
            - cmsworks-redis
            - mailer
    cmsworks-postgres:
        image: postgres:11.2-alpine
        volumes:
            - cmsworks-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: developer
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: cmsworks
        ports:
            - "54321:5432"
    mailer:
        image: mailhog/mailhog
        ports:
            - "8082:8025"
    cmsworks-node-watch:
        image: node:12.7-alpine
        volumes:
            - ./app:/app
        working_dir: /app
        command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run watch"
    cmsworks-node:
        image: node:12.7-alpine
        volumes:
            - ./app:/app
        working_dir: /app
    cmsworks-redis:
        image: redis:5.0-alpine
        volumes:
            - cmsworks-redis:/data
        command:
            - 'redis-server'
            - '--databases 2'
            - '--save 900 1'
            - '--save 300 10'
            - '--save 60 10000'
            - '--requirepass secret'
volumes:
    cmsworks-postgres:
    cmsworks-redis:
    composer:

networks:
    cmsworks_default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.220.0/28
